WebStoreCoreApplication/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStoreCoreApplication.Controllers.Infrastructure;

namespace WebStoreCoreApplication.Controllers
{
    public class BaseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Page404()
        {
            return View();
        }

        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult Blog_Single()
        {
            return View();
        }
       
        public IActionResult Cart()
        {
            return View();
        }

        public IActionResult Checkout()
        {
            return View();
        }

        public IActionResult ContactUs()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        

    }
}

WebStoreCoreApplication/Views/Shared/Footer/FootBot.cshtml
<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
            <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
        </div>
    </div>
</div>

WebStoreCoreApplication/Views/Shared/Footer/FootTop.cshtml
<div class="footer-top">
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <div class="companyinfo">
                    <h2><span>e</span>-shopper</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                </div>
            </div>
            <div class="col-sm-7">
                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <img src="~/images/home/iframe1.png" alt="" />
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <img src="~/images/home/iframe2.png" alt="" />
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <img src="~/images/home/iframe3.png" alt="" />
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="video-gallery text-center">
                        <a href="#">
                            <div class="iframe-img">
                                <img src="~/images/home/iframe4.png" alt="" />
                            </div>
                            <div class="overlay-icon">
                                <i class="fa fa-play-circle-o"></i>
                            </div>
                        </a>
                        <p>Circle of Hands</p>
                        <h2>24 DEC 2014</h2>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="address">
                    <img src="~/images/home/map.png" alt="" />
                    <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                </div>
            </div>
        </div>
    </div>
</div>

WebStoreCoreApplication/Views/Shared/Footer/FootWid.cshtml
<div class="footer-widget">
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Service</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Online Help</a></li>
                        <li><a a asp-controller="Base" asp-action="ContactUs">Contact Us</a></li>
                        <li><a href="#">Order Status</a></li>
                        <li><a href="#">Change Location</a></li>
                        <li><a href="#">FAQ’s</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Quock Shop</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">T-Shirt</a></li>
                        <li><a href="#">Mens</a></li>
                        <li><a href="#">Womens</a></li>
                        <li><a href="#">Gift Cards</a></li>
                        <li><a href="#">Shoes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>Policies</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privecy Policy</a></li>
                        <li><a href="#">Refund Policy</a></li>
                        <li><a href="#">Billing System</a></li>
                        <li><a href="#">Ticket System</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="single-widget">
                    <h2>About Shopper</h2>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Store Location</a></li>
                        <li><a href="#">Affillate Program</a></li>
                        <li><a href="#">Copyright</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-3 col-sm-offset-1">
                <div class="single-widget">
                    <h2>About Shopper</h2>
                    <form action="#" class="searchform">
                        <input type="text" placeholder="Your email address" />
                        <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                        <p>Get the most recent updates from <br />our site and be updated your self...</p>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>