WebStoreCoreApplication/ViewModels/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebStoreCoreApplication.ViewModels
{
    public class Cart
    {
        public List<CartItem> Items { get; set; }
        public int ItemsCount => Items?.Sum(x => x.Quantity) ?? 0;
    }
}

WebStoreCoreApplication/ViewModels/CartViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace WebStoreCoreApplication.ViewModels
{ 
    public class CartViewModel
    {
        public Dictionary<ProductViewModel, int> Items { get; set; }
        public int ItemsCount => Items?.Sum(x => x.Value) ?? 0;
    }
}

WebStoreCoreApplication/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStoreCoreApplication.Controllers.Infrastructure.Interfaces;
using WebStoreCoreApplication.ViewModels;

namespace WebStoreCoreApplication.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IOrdersService _ordersService;

        public CartController(ICartService cartService, IOrdersService ordersService)
        {
            _cartService = cartService;
            _ordersService = ordersService;
        }

        public IActionResult Details()
        {
            var model = new OrderDetailsViewModel()
            {
                CartViewModel = _cartService.TransformCart(),
                OrderViewModel = new OrderViewModel()
            };

            return View(model);
        }

        public IActionResult DecrementFromCart(int id)
        {
            _cartService.DecrementFromCart(id);
            return RedirectToAction("Details");
        }

        public IActionResult RemoveFromCart(int id)
        {
            _cartService.RemoveFromCart(id);
            return RedirectToAction("Details");
        }

        public IActionResult RemoveAll()
        {
            _cartService.RemoveAll();
            return RedirectToAction("Details");
        }

        public IActionResult AddToCart(int id, string returnUrl)
        {
            _cartService.AddToCart(id);
            return Redirect(returnUrl);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CheckOut(OrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                var orderResult = _ordersService.CreateOrder(model, _cartService.TransformCart(), User.Identity.Name);

                _cartService.RemoveAll();

                return RedirectToAction("OrderConfirmed", new { id = orderResult.Id });
            }

            var detailsModel = new OrderDetailsViewModel
            {
                CartViewModel = _cartService.TransformCart(),
                OrderViewModel = model
            };
            return View("Details", detailsModel);

        }

        public IActionResult OrderConfirmed(int id)
        {
            ViewBag.OrderId = id;
            return View();
        }
    }
}

WebStoreCoreApplication/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStoreCoreApplication.Controllers.Infrastructure.Interfaces;
using WebStoreCoreApplication.Domain.Entities;
using WebStoreCoreApplication.ViewModels;

namespace WebStoreCoreApplication.Controllers
{
        public class CatalogController : Controller
    {
        private readonly IProductServices _productServices;

        public CatalogController(IProductServices productService)
        {
            _productServices = productService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProductDetails(int id)
        {
            var product = _productServices.GetProductById(id);
            if (product == null) return NotFound();
            /*
            Мой вариант дз 7
            return View(product);
            */

            return View(new ProductViewModel
            {
                Id = product.Id,
                ImageUrl = product.ImageUrl,
                Name = product.Name,
                Order = product.Order,
                Price = product.Price,
                BrandName = product.Brand?.Name ?? string.Empty
            });

        }

        public IActionResult Shop(int? categoryId, int? brandId)
        {
            var products = _productServices.GetProducts(new ProductFilter { BrandId = brandId, CategoryId = categoryId });

            var model = new CatalogViewModel()
            {
                BrandId = brandId,
                CategoryId = categoryId,
                Products = products.Select(pr => new ProductViewModel()
                {
                    Id = pr.Id,
                    ImageUrl = pr.ImageUrl,
                    Name = pr.Name,
                    Order = pr.Order,
                    Price = pr.Price
                }).OrderBy(p => p.Order).ToList()
            };

            return View(model);
        }
    }
}

WebStoreCoreApplication/Views/Cart/Details.cshtml
@model WebStoreCoreApplication.ViewModels.OrderDetailsViewModel

@{
    ViewData["Title"] = "Корзина";
}

<section id="cart_items">
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">Shopping Cart</li>
        </ol>
    </div>
    <div class="table-responsive cart_info">
        <table class="table table-condensed">
            <thead>
                <tr class="cart_menu">
                    <td class="image">Item</td>
                    <td class="description"></td>
                    <td class="price">Price</td>
                    <td class="quantity">Quantity</td>
                    <td class="total">Total</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
            @{
                var sumCart = 0m;
            }
            @foreach (var item in Model.CartViewModel.Items)
            {
               sumCart += (item.Value * item.Key.Price);

                <tr>
                    <td class="cart_product">
                        <a href=""><img src="~/images/shop/@item.Key.ImageUrl" alt=""></a>
                    </td>
                    <td class="cart_description">
                        <h4>
                            <a asp-action="ProductDetails"
                               asp-controller="Catalog"
                               asp-route-id="@item.Key.Id">
                                @item.Key.Name
                            </a>
                        </h4>
                        <p>Web ID: 1089772</p>
                    </td>
                    <td class="cart_price">
                        <p>@(item.Key.Price.ToString("C"))</p>
                    </td>
                    <td class="cart_quantity">
                        <div class="cart_quantity_button">
                            <a asp-controller="Cart"
                               asp-action="AddToCart"
                               asp-route-id="@item.Key.Id"
                               asp-route-returnUrl="@Context.Request.Path"
                               class="cart_quantity_up">
                                + </a>
                            <input class="cart_quantity_input" type="text" name="quantity" value="@item.Value" autocomplete="off" size="2">
                            <a asp-controller="Cart"
                               asp-action="DecrementFromCart"
                               asp-route-id="@item.Key.Id"
                               class="cart_quantity_down">
                                - </a>
                        </div>
                    </td>
                    <td class="cart_total">
                        <p class="cart_total_price">
                            @((item.Value * item.Key.Price).ToString("C"))
                        </p>
                    </td>
                    <td class="cart_delete">
                        <a class="cart_quantity_delete"
                           asp-controller="Cart"
                           asp-action="RemoveFromCart"
                           asp-route-id="@item.Key.Id">
                            <i class="fa fa-times"></i></a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>

</section> <!--/#cart_items-->

<section id="do_action">

    <div class="heading">
        <h3>Оформите заказ</h3>
    </div>
    <div class="row login-form">
        @await Html.PartialAsync("_OrderPartial", Model.OrderViewModel, 
            new ViewDataDictionary(ViewData) { { "sumCart", sumCart } })
    </div>

</section><!--/#do_action-->

WebStoreCoreApplication/Views/Cart/OrderConfirmed.cshtml
@{
    ViewData["Title"] = "Ваш заказ принят";
}

<h2>Ваш заказ под номером @ViewBag.OrderId принят и в скором времени будет обработан</h2>

WebStoreCoreApplication/Views/Cart/_OrderPartial.cshtml
@model OrderViewModel

<form method="post" asp-antiforgery="true" asp-action="CheckOut">
    <div class="col-sm-6">
        <input asp-for="Name" placeholder="@nameof(@Model.Name)" />
        <span asp-validation-for="Name" class="text-danger"></span>

        <input asp-for="Phone" placeholder="@nameof(Model.Phone)" />
        <span asp-validation-for="Phone" class="text-danger"></span>

        <input asp-for="Address" placeholder="@nameof(Model.Address)" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    @{
        ViewData.TryGetValue("sumCart", out var sumObj);
    }
    <div class="col-sm-6">
        <div class="total_area">
            @if (sumObj != null)
            {
                var sum = (decimal)sumObj;
                <ul>
                    <li>Итого <span>@sum.ToString("C")</span></li>
                </ul>
                if (sum > 0)
                {
                    <input type="submit" value="Оформить заказ" class="btn btn-default check_out" />
                }
            }
        </div>
    </div>
</form>